var phylopic;
(function(g){(function(a){var e=function(){function a(){this.fake=!0;this._boundary="--------FormData"+Math.random();this._fields=[]}a.prototype.append=function(d,b){this._fields.push([d,b])};a.prototype.toString=function(){for(var d="",b=0,f=this._fields.length;b<f;++b)var c=this._fields[b],a=c[1],d=d+("--"+this._boundary+'/r/nContent-Disposition: form-data; name="'+c[0]+";"),d=a.name?d+(' filename="'+a.name+'"/r/nContent-Type: '+a.type+"/r/n/r/n"+a.getAsBinary()+"/r/n"):d+("/r/n/r/n"+a+"/r/n");
return d+"--"+this._boundary+"--"};return a}();a.init=function(a){a.FormData||(a.FormData=e);a.console||(a.console={log:function(){for(var d=0;d<arguments.length;d++);}});a=a.console;a.debug||(a.debug=a.log);a.warn||(a.warn=a.log);a.error||(a.error=a.warn)}})(g.polyfill||(g.polyfill={}))})(phylopic||(phylopic={}));phylopic.polyfill.init(window);
(function(g){(function(a){a.init=function(){var a=ko.bindingHandlers;a.fadeVisible={init:function(a,d,b){var f=b();b=f.fadeInDelay||0;d=!!ko.utils.unwrapObservable(d());!d||0<b?($(a).hide(),d&&(d=f.fadeInDuration||"fast",$(a).delay(b).fadeIn(d))):$(a).show()},update:function(a,d,b){b=b();ko.utils.unwrapObservable(d())?(d=b.fadeInDelay||0,b=b.fadeInDuration||"fast",$(a).stop(!0).delay(d).fadeIn(b)):(d=b.fadeOutDelay||0,b=b.fadeOutDuration||"fast",$(a).stop(!0).delay(d).fadeOut(b))}};a.modal={init:function(a,
d){$(a).addClass("modal").hide().modal(ko.utils.unwrapObservable(d())?"show":"hide")},update:function(a,d){$(a).modal(ko.utils.unwrapObservable(d())?"show":"hide")}};a.popover={init:function(a,d){ko.utils.unwrapObservable(d())&&$(a).popover()}};a.scrollTop={update:function(a,d,b){if(ko.utils.unwrapObservable(d())){var f=b();d=f.scrollOffset||0;b=f.scrollEasing||"swing";f=f.scrollDuration||400;$("body").animate({scrollTop:$(a).offset().top+d},f,b)}}};a.slideVisible={init:function(a,d,b){var f=b();
b=f.slideDownDelay||0;d=!!ko.utils.unwrapObservable(d());!d||0<b?($(a).hide(),d&&(d=f.slideDownDuration||"fast",$(a).delay(b).slideDown(d))):$(a).show()},update:function(a,d,b){b=b();ko.utils.unwrapObservable(d())?(d=b.slideDownDelay||0,b=b.slideDownDuration||"fast",$(a).stop(!0).delay(d).slideDown(b)):(d=b.slideUpDelay||0,b=b.slideUpDuration||"fast",$(a).stop(!0).delay(d).slideUp(b))}}}})(g.bindings||(g.bindings={}))})(phylopic||(phylopic={}));phylopic.bindings.init();
(function(g){(function(a){function e(a){var b=$.Deferred();$.ajax(a).fail(function(f,c,a){b.reject({code:c?c:"fail",message:(a?String(a):"Error loading data")+".",details:f})}).done(function(f){try{f.success?b.resolve(f.result):(console.error(f.fault),b.reject(f.fault))}catch(c){console.error(c),b.reject({code:c.name,details:c.stack,message:c.message})}});return h(b.promise())}function h(a){return a}a.NAME_TYPE_SCIENTIFIC="scientific";a.NAME_TYPE_VERNACULAR="vernacular";a.NOTIFICATION_TYPE_DATA="data";
a.NOTIFICATION_TYPE_FAULT="fault";a.NOTIFICATION_TYPE_MESSAGE="message";a.NOTIFICATION_TYPE_PROGRESS="progress";a.ajax=e;a.auto=function(a){void 0===a&&(a=null);var b=$.Deferred();b.resolve(a);return h(b.promise())};a.autoError=function(a){var b=$.Deferred();b.reject(a);return h(b.promise())};a.combineOptions=function(a,b){if(!a)return b?b:[];if(!b)return a;for(var f=[],c=0,n=a.length;c<n;++c){var e=a[c];0>$.inArray(e,f)&&f.push(e)}c=0;for(n=b.length;c<n;++c)e=b[c],0>$.inArray(e,f)&&f.push(e);return f};
a.copyImage=function(a,b){b.credit=a.credit;b.directNames=a.directNames.concat();b.licenseURL=a.licenseURL;b.pngFiles=a.pngFiles.concat();b.submitted=a.submitted;b.submitter=a.submitter;b.svgFile=a.svgFile;b.taxa=a.taxa.concat()};a.defer=function(){return $.Deferred()};a.get=function(a,b,f){void 0===b&&(b=void 0);void 0===f&&(f=!1);return e({cache:f,contentType:"application/json",data:b,dataType:"json",type:"GET",url:a})};a.notifyData=function(a,b){void 0===b&&(b="data");return{data:a,type:b}};a.notifyFault=
function(d){return{fault:d,type:a.NOTIFICATION_TYPE_FAULT}};a.notifyMessage=function(d){return{message:d,type:a.NOTIFICATION_TYPE_MESSAGE}};a.notifyProgress=function(d,b){return{loaded:d,total:b,type:a.NOTIFICATION_TYPE_PROGRESS}};a.post=function(a,b){void 0===b&&(b=void 0);var f={cache:!1,contentType:"application/json",data:b,dataType:"json",type:"POST",url:a};b instanceof FormData&&(f.contentType=!1,f.processData=!1);return e(f)};a.withOptions=function(a,b){if(b&&0<b.length){var f={options:b.join(" ")},
c;for(c in a)"options"!==c&&(f[c]=a[c]);return f}return a}})(g.api||(g.api={}))})(phylopic||(phylopic={}));
(function(g){(function(a){(function(e){e.add=function(e){return a.post("/api/a/account/add",e)};e.check=function(){return a.get("/api/a/account/check")};e.edit=function(e){for(var d=[],b=1;b<arguments.length;b++)d[b-1]=arguments[b];return a.post("/api/a/account/edit",a.withOptions(e,d))};e.get=function(e){void 0===e&&(e=null);var d="/api/a/account";null!==e&&(d+="/"+e);return a.get(d)};e.images=function(e){for(var d=[],b=1;b<arguments.length;b++)d[b-1]=arguments[b];b="/api/a/account";e.uid&&(b+="/"+
e.uid);b+="/images/"+e.start+"/"+e.length;return a.get(b,a.withOptions({},d))};e.imagesCount=function(e){void 0===e&&(e=null);return null!==e?a.get("/api/a/account/"+e+"/images/count"):a.get("/api/a/account/images/count")};e.login=function(e){for(var d=[],b=1;b<arguments.length;b++)d[b-1]=arguments[b];return a.post("/api/a/account/login",a.withOptions(e,d))};e.logout=function(){return a.post("/api/a/account/logout")};e.passwordResetRequest=function(e){return a.post("/api/a/account/password/reset/request",
{email:e})}})(a.account||(a.account={}))})(g.api||(g.api={}))})(phylopic||(phylopic={}));
(function(g){(function(a){(function(a){var h=function(){function a(b,f,c,d){void 0===b&&(b=null);void 0===f&&(f=!0);void 0===c&&(c="Loading");void 0===d&&(d=!0);this.allowFaultDismiss=ko.observable(!0);this.fault=ko.observable();this.cancelled=ko.observable(!1);this.message=ko.observable(null);this.indeterminate=ko.observable(!1);this.loaded=ko.observable(NaN);this.pending=ko.observable(!1);this.rejected=ko.observable(!1);this.resolved=ko.observable(!1);this.result=ko.observable();this.state=ko.observable(null);
this.total=ko.observable(NaN);this.warnings=ko.observableArray([]);var e=this;this.promise=b;this.indeterminate(f);this.message(c);this.allowFaultDismiss(d);this.scale=ko.computed(function(){return e.indeterminate()?"100%":Math.max(1,Math.floor(100*e.loaded()/e.total()))+"%"});this._updateState();this._watch()}a.prototype.dismissFault=function(){this.fault(null);this.cancelled(!0)};a.prototype.dismissWarning=function(b){this.warnings.remove(b)};a.prototype._updateState=function(){var b=this.promise?
this.promise.state():null,a=this;this.promise&&("rejected"===b?this.promise.fail(function(b){return a.fault(b)}).fail(function(b){return a.cancelled("cancel"===b.code)}):"resolved"===b?this.promise.done(function(b){return a.result(b)}):b="pending");this.state(b);this.pending("pending"===b);this.rejected("rejected"===b);this.resolved("resolved"===b)};a.prototype._watch=function(){function b(){c.message(null);c._updateState()}function a(b){switch(b.type){case g.api.NOTIFICATION_TYPE_FAULT:c.warnings.push(b.fault);
break;case g.api.NOTIFICATION_TYPE_MESSAGE:c.message(b.message);break;case g.api.NOTIFICATION_TYPE_PROGRESS:c.loaded(b.loaded),c.total(b.total),c.indeterminate(!(0<b.total))}}if(this.promise){var c=this;this.promise.progress(a).always(b)}};return a}();a.Promise=h;a.EMPTY_PROMISE=new h})(a.async||(a.async={}))})(g.vm||(g.vm={}))})(phylopic||(phylopic={}));
(function(g){(function(a){(function(e){function h(b,f){for(var c=[],d=2;d<arguments.length;d++)c[d-2]=arguments[d];return a.get("/api/a/name/"+b+"/taxonomy",a.withOptions(f,c),!0)}e.NO_MATCH_FAULT={code:"nomatch",message:"No matches found.",details:null};e.EMPTY_IMAGES_RESULT={other:[],same:[],subtaxa:[],supertaxa:[]};e.TAXA_ALL="all";e.TAXA_IMMEDIATE="immediate";e.TAXA_NONE="none";var d={other:!1,subtaxa:!1,supertaxa:!1};e.add=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];
return a.post("/api/a/name/add",a.withOptions(b,f))};e.addSet=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];c={nameUIDs:b.join(" ")};return a.get("/api/a/name/set/add",a.withOptions(c,f))};e.deleteName=function(b){return a.post("/api/a/name/"+b+"/delete")};e.edit=function(b,f){for(var c=[],d=2;d<arguments.length;d++)c[d-2]=arguments[d];return a.post("/api/a/name/"+b+"/edit",a.withOptions(f,c))};e.get=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];
return a.get("/api/a/name/"+b,a.withOptions({},f))};e.getSet=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];return a.get("/api/a/name/set/"+b,a.withOptions({},f))};e.images=function(b,f){void 0===f&&(f=null);for(var c=[],d=2;d<arguments.length;d++)c[d-2]=arguments[d];null===f&&(f={});return a.get("/api/a/name/"+b+"/images",a.withOptions(f,c))};e.imagesMultiple=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];var e=function(){function c(b){l.notify(a.notifyFault(b))}
function p(b){$.each(b.same,function(b,a){k[a.uid]||(k[a.uid]=!0,h.push(a))})}m>=b.length?l.resolve(h):(l.notify(a.notifyProgress(m,b.length)),g.api.name.images.apply(null,[b[m++],d].concat(f)).fail(c).done(p).always(e))},k={},h=[],m=0,l=a.defer();e();return l.promise()};e.minSupertaxa=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];return 0<b.length?(c={nameUIDs:b.join(" ")},a.get("/api/a/name/minSupertaxa",a.withOptions(c,f))):a.auto([])};e.search=function(b){for(var f=[],
c=1;c<arguments.length;c++)f[c-1]=arguments[c];return(b=b?$.trim(b):null)&&2<=b.length?a.get("/api/a/name/search",a.withOptions({text:b},f)):a.auto([])};e.taxonomy=h;e.taxonomyMultiple=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];return a.get("/api/a/name/taxonomy/multiple",a.withOptions({nameUIDs:b.join(" ")},f),!0)};e.taxonomySet=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];return a.get("/api/a/name/set/"+b+"/taxonomy",a.withOptions({},f),!0)};
e.taxonomySources=function(b){for(var f=[],c=1;c<arguments.length;c++)f[c-1]=arguments[c];return a.get("/api/a/name/"+b+"/taxonomy/sources",a.withOptions({},f),!0)};e.taxonomyUBio=function(b,f){function c(b){function f(e){function g(b){l.notify(a.notifyFault(b))}function h(){f(e+1)}l.notify(a.notifyProgress(e+1,c+2));if(e>=c)2<=p?m.useUBio=!1:p++,d();else{var k=b.commands[e];l.notify(a.notifyMessage(k.title));a.get(k.url,void 0,!0).fail(g).always(h)}}if(b.uBioCommands){var c=b.commands.length;f(0)}else l.resolve(b)}
function d(){l.notify(a.notifyMessage("Loading taxonomy"));h.apply(null,u).fail(l.reject).done(c)}void 0===f&&(f=null);for(var e=[],g=2;g<arguments.length;g++)e[g-2]=arguments[g];var m={useUBio:!0},l=a.defer(),u=[b,m].concat(e),p=1;null!==f&&("string"===typeof f.options&&(m.options=f.options),"string"===typeof f.subtaxa&&(m.subtaxa=f.subtaxa),"string"===typeof f.supertaxa&&(m.supertaxa=f.supertaxa));d();return l.promise()};e.toggle=function(b,f){void 0===f&&(f=null);var c={};null!==f&&(c.enabled=
f);return a.post("/api/a/name/"+b+"/toggle",c)}})(a.name||(a.name={}))})(g.api||(g.api={}))})(phylopic||(phylopic={}));
(function(g){(function(a){function e(b){return 0<b.citationStart?$.trim(b.string.substr(0,b.citationStart)):b.string}function g(b,a){return b<a?-1:a<b?1:0}function d(b,a){if(b==a)return 0;if(!b||!b.string)return a&&a.string?-1:0;if(!a||!a.string)return 1;if(b.uid===a.uid)return 0;var c=e(b),d=e(a),k=g(c.toUpperCase(),d.toUpperCase());if(0!==k)return k;k=g(c,d);if(0!==k)return k;k=g(b.string.toUpperCase(),a.string.toUpperCase());return 0!==k?k:g(b.string,a.string)}a.names=d;a.taxa=function(b,a){return d(b.canonicalName,
a.canonicalName)}})(g.compare||(g.compare={}))})(phylopic||(phylopic={}));
(function(g){(function(a){function e(b){return 0<b.citationStart?$.trim(b.string.substr(b.citationStart)):""}function g(b){for(var a=!1,c=null,d=!1,e=-1,h=0,m=b.length;h<m;++h){var l=b.charAt(h);if("+"===l||"/"===l||"-"===l)a=!1;else if(d&&")"===l){if(/^[0-9]$/.test(c))return[b.substr(0,e),b.substr(e)];d=!1}else if(/^[A-Z]$/.test(l))if(!d&&a)if("("===c)e=h-1,d=!0;else return[b.substr(0,h),b.substr(h)];else a=!0;c=l}return[b]}function d(b){return 0<b.citationStart?$.trim(b.string.substr(0,b.citationStart)):
b.string}a.citation=e;a.guessCitationStart=function(b){var a=0;if("vernacular"!==b.type){var c=g(b.string);1<c.length&&(a=c[0].length)}return a<b.string.length?a:0};a.guessHyperonym=function(b){var a=d(b);b=e(b);var c,g="";/^[\(\[\{].+[\)\]\}]$/.test(b)&&(b="");if(c=a.match(/^([A-Z][a-z]+)\s+\(([A-Z][a-z]+)\)$/))g=c[1];else if(a=a.replace(/\([A-Z][a-z]+\)\s*/,""),c=a.match(/^([A-Z][a-z]+)\s+([a-z][a-z]+)\s+([a-z][a-z]+)$/))g=c[1]+" "+c[2];else if(c=a.match(/^([A-Z][a-z]+)\s+([a-z][a-z]+)$/))g=c[1];
else if(c=a.match(/^([A-Z][a-z]+)idae$/))g=c[1]+"oidea";else if(c=a.match(/^([A-Z][a-z]+)inae$/))g=c[1]+"idae";else if(c=a.match(/^([A-Z][a-z]+)ini$/))g=c[1]+"inae";else if(c=a.match(/^([A-Z][a-z]+)aceae$/))g=c[1]+"ineae";else if(c=a.match(/^([A-Z][a-z]+)oideae$/))g=c[1]+"aceae";else if(c=a.match(/^([A-Z][a-z]+)ineae$/))g=c[1]+"ales";return""===g?"":""===b?g:g+" "+b};a.guessHyponym=function(b){var a=d(b);b=e(b);var c,g="";/^[\(\[\{].+[\)\]\}]$/.test(b)&&(b="");if(c=a.match(/^([A-Z][a-z]+)\s+\(([a-z][a-z]+)\)$/))g=
c[1]+" "+c[2];else if(a=a.replace(/\([A-Z][a-z]+\)\s*/,""),c=a.match(/^([A-Z][a-z]+)\s+([a-z][a-z]+)$/))g=c[1]+" "+c[2]+" "+c[2];else if(c=a.match(/^([A-Z][a-z]+)oidea$/))g=c[1]+"idae";else if(c=a.match(/^([A-Z][a-z]+)idae$/))g=c[1]+"inae";else if(c=a.match(/^([A-Z][a-z]+)inae$/))g=c[1]+"ini";else if(c=a.match(/^([A-Z][a-z]+)ini$/))g=c[1]+"ina";else if(c=a.match(/^([A-Z][a-z]+)aceae$/))g=c[1]+"oideae";else if(c=a.match(/^([A-Z][a-z]+)ales$/))g=c[1]+"ineae";else if(c=a.match(/^([A-Z][a-z]+)ineae$/))g=
c[1]+"aceae";return""===g?"":""===b?g:g+" "+b};a.guessType=function(b){return/^[A-Z]/.test(b)?"scientific":"vernacular"};a.splitScientificNameString=g;a.uncite=d})(g.nomina||(g.nomina={}))})(phylopic||(phylopic={}));
(function(g){(function(a){(function(e){var h=function(){function d(b,f,c){void 0===b&&(b=null);void 0===f&&(f=!1);void 0===c&&(c="");this.citation=ko.observable("");this.nomen=ko.observable("");this.progress=ko.observable(a.async.EMPTY_PROMISE);this.sections=ko.observable([]);this.state=ko.observable(null);this.text=ko.observable("");this.taxa=ko.observableArray([]);this.type=ko.observable("scientific");this._deferred=g.api.defer();var d=this;this.allowCreation=f;this._initComputed();this.promise().done(function(){return d.state(null)});
"string"===typeof b?(b=$.trim(b),0<b.length&&(this.text(b),this.searchText())):(this.text($.trim(c)),this._deferred.notify(g.api.notifyMessage("Getting name")),this.state("input"))}d.prototype.cancel=function(){this._deferred.reject({code:"cancel",message:"Search cancelled."})};d.prototype.create=function(){var b=this,f=this.type(),c="scientific"===f,d=$.trim(this.nomen()),e=$.trim(this.citation());this.progress(new a.async.Promise(g.api.name.add({citationStart:c&&0<e.length?d.length+1:0,string:c?
d+" "+e:d,type:f},"citationStart","html","string","type").done(function(a){b._deferred.resolve({canonicalName:a,icon:null,illustrated:!1,names:[a]})})))};d.prototype.promise=function(){return this._deferred.promise()};d.prototype.searchText=function(){function b(b){function a(){for(var e=b.length,h=[{label:"Best Matches",taxa:[]},{label:"Possible Matches",taxa:[]}],l=d.text().toUpperCase(),k=0;k<e;++k){var p=b[k],n;a:{n=l;for(var s=p,q=0,v=s.names.length;q<v;++q){var r=s.names[q],t=r.string.toUpperCase();
if(t===n||0<r.citationStart&&$.trim(t.substr(0,r.citationStart))===n){n=!0;break a}}n=!1}n?h[0].taxa.push(p):h[p.illustrated?0:1].taxa.push(p)}for(k=h.length-1;0<=k;--k)0===h[k].taxa.length?h.splice(k,1):h[k].taxa.sort(g.compare.taxa);return h}if(0===b.length){if(d.allowCreation){d.type(g.nomina.guessType(d.text()));var e={uid:null,citationStart:0,string:d.text(),type:d.type()},e=g.nomina.guessCitationStart(e);0<e?(d.nomen($.trim(d.text().substr(0,e))),d.citation($.trim(d.text().substr(e)))):(d.nomen(d.text()),
d.citation(""))}d.state("retry")}else 1===b.length?d._deferred.resolve(b[0]):(d._deferred.notify(g.api.notifyMessage("Selecting taxon")),d.sections(a()),d.state("select"))}var d=this;this.text($.trim(this.text()));2>this.text().length?d._deferred.reject({code:"empty",message:"Insufficient text provided."}):(this.state("search"),g.api.name.search(this.text(),"canonicalName","citationStart","icon","illustrated","names","html","string","type").progress(this._deferred.notify).fail(this._deferred.reject).done(b),
this.progress(new a.async.Promise(this.promise(),!0,"Searching",!1)))};d.prototype.select=function(b){this._deferred.resolve(b)};d.prototype._initComputed=function(){var b=this;this.illustratedTaxa=ko.computed(function(){for(var a=b.taxa(),c=[],d=0,e=a.length;d<e;++d){var g=a[d];g.illustrated&&c.push(g)}return c})};return d}();e.Search=h})(a.name||(a.name={}))})(g.vm||(g.vm={}))})(phylopic||(phylopic={}));
(function(g){(function(a){var e=function(){function a(){this.isAdmin=ko.observable(!1);this.loggedIn=ko.observable(!1);this.loggedOut=ko.observable(!1);this.taxonSearch=ko.observable();this._checkAccount()}a.prototype._checkAccount=function(){var a=this;this.checkAccountPromise=g.api.account.check().done(function(b){a.loggedIn("string"===typeof b);a.loggedOut(!a.loggedIn());a.isAdmin("administrator"===b)})};a.prototype.cancelTaxonSearch=function(){this.taxonSearch()&&(this.taxonSearch().cancel(),
this.taxonSearch(null))};a.prototype.startTaxonSearch=function(a){void 0===a&&(a=null);a=new g.vm.name.Search(a,this.isAdmin());this.taxonSearch(a);a.promise().done(function(a){a&&(location.href="/name/"+a.canonicalName.uid)})};return a}();a.Page=e})(g.page||(g.page={}))})(phylopic||(phylopic={}));
