var __extends=this&&this.__extends||function(a,q){function c(){this.constructor=a}for(var r in q)q.hasOwnProperty(r)&&(a[r]=q[r]);a.prototype=null===q?Object.create(q):(c.prototype=q.prototype,new c)},phylopic;
(function(a){(function(a){(function(c){c.add=function(c,k){return a.post("/api/a/hyponymy/"+c+"/"+k+"/add")};c.toggle=function(c,k,n){void 0===n&&(n=null);var p={};null!==n&&(p.enabled=n);return a.post("/api/a/hyponymy/"+c+"/"+k+"/toggle",p)}})(a.hyponymy||(a.hyponymy={}))})(a.api||(a.api={}))})(phylopic||(phylopic={}));
(function(a){(function(a){(function(c){c.add=function(c,k){return a.post("/api/a/synonymy/"+c+"/"+k+"/add")};c.flip=function(c,k){for(var n=[],p=2;p<arguments.length;p++)n[p-2]=arguments[p];return a.post("/api/a/synonymy/"+c+"/"+k+"/flip",a.withOptions({},n))};c.toggle=function(c,k,n){void 0===n&&(n=null);var p={};null!==n&&(p.enabled=n);return a.post("/api/a/synonymy/"+c+"/"+k+"/toggle",p)}})(a.synonymy||(a.synonymy={}))})(a.api||(a.api={}))})(phylopic||(phylopic={}));
(function(a){(function(q){(function(c){function q(a){for(var e=0,m=c.LICENSES.length;e<m;++e)if(c.LICENSES[e].url===a)return c.LICENSES[e];return null}var k={code:"by",description:"You must give appropriate credit, provide a link to the license, and indicate if changes were made. You may do so in any reasonable manner, but not in any way that suggests the licensor endorses you or your use.",label:"Attribution",useInComparison:!0},n={code:"nc",description:"You may not use the material for commercial purposes, including use in commercial publications or websites.",
label:"Noncommercial",useInComparison:!0},p={code:"remix",description:"You are free to to adapt the work.",label:"Remix",useInComparison:!1},s={code:"sa",description:"If you remix, transform, or build upon the material, you must distribute your contributions under the same or similar license to this one.",label:"Share Alike",useInComparison:!0},b={code:"share",description:"You are free to copy, distribute and transmit the work.",label:"Share",useInComparison:!0};c.LICENSES=[{code:"cc-0",components:[{code:"nolaw",
description:"The person who associated a work with this deed has dedicated the work to the public domain by waiving all of his or her rights to the work worldwide under copyright law, including all related and neighboring rights, to the extent allowed by law.",label:"No Copyright",useInComparison:!1}],label:"Public Domain Dedication 1.0",publicDomain:!0,url:"http://creativecommons.org/publicdomain/zero/1.0/"},{code:"pdm",components:[{code:"noc",description:"This work has been identified as being free of known restrictions under copyright law, including all related and neighboring rights.",
label:"No Copyright",useInComparison:!1}],label:"Public Domain Mark 1.0",publicDomain:!0,url:"http://creativecommons.org/publicdomain/mark/1.0/"},{code:"cc-by",components:[b,p,k],label:"Creative Commons Attribution 3.0 Unported",publicDomain:!1,url:"http://creativecommons.org/licenses/by/3.0/"},{code:"cc-by-sa",components:[b,p,k,s],label:"Creative Commons Attribution-ShareAlike 3.0 Unported",publicDomain:!1,url:"http://creativecommons.org/licenses/by-sa/3.0/"},{code:"cc-by-nc",components:[b,p,k,n],
label:"Creative Commons Attribution-NonCommercial 3.0 Unported",publicDomain:!1,url:"http://creativecommons.org/licenses/by-nc/3.0/"},{code:"cc-by-nc-sa",components:[b,p,k,n,s],label:"Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported",publicDomain:!1,url:"http://creativecommons.org/licenses/by-nc-sa/3.0/"}];c.canChangeLicense=function(a,e){if(a===e||e.publicDomain)return!0;for(var m=0;m<e.components.length;++m)if(0>a.components.indexOf(e.components[m]))return!1;return!0};c.licenseByURL=
q;k=function(){function d(e){this._directNameUIDs={};e.taxa&&e.taxa.sort(a.compare.taxa);if(e.directNames){e.directNames.sort(a.compare.names);for(var d=0,b=e.directNames.length;d<b;++d)this._directNameUIDs[e.directNames[d].uid]=!0}this.image=e}d.prototype.byline=function(){var a=this.image.credit;return"string"!==typeof a||""===a?"(uncredited)":"by "+a};d.prototype.contactURL=function(){return this.image.submitter.allowContact?"/contact/"+this.image.submitter.uid+"/PhyloPic%20Image":null};d.prototype.hasDirectName=
function(a){if(a.names)for(var d=0,b=a.names.length;d<b;++d)if(this._directNameUIDs[a.names[d].uid])return!0;return"object"===typeof a.canonicalName&&this._directNameUIDs[a.canonicalName.uid]};d.prototype.license=function(){return q(this.image.licenseURL)};d.prototype.popoverContent=function(){var a=[this.title(),this.byline()],d=this.license();d&&a.push(d.label);return a.join("<hr />")};d.prototype.reportURL=function(){return"/image/"+this.image.uid+"/report/"};d.prototype.taxa=function(){return this.image.taxa};
d.prototype.thumbURL=function(){return"/assets/images/submissions/"+this.image.uid+".thumb.png"};d.prototype.title=function(){var d=[],b=this.image.directNames.sort(a.compare.names);$.each(b,function(a,b){b&&b.html&&d.push(b.html)});return d.join("<br />")};d.prototype.url=function(){return"/image/"+this.image.uid};return d}();c.Image=k})(q.image||(q.image={}))})(a.vm||(a.vm={}))})(phylopic||(phylopic={}));
(function(a){(function(q){(function(c){function r(c,b){function d(a){var d=a.string.toUpperCase();0<a.citationStart&&(d=d.substr(0,a.citationStart));return $.trim(d)}var e={},m=c.length;if(0===m)return c;for(var t=d(b),f=0;f<m;++f){var g=c[f],h=d(g);if(h!==t){var l=e[h];e[h]=l?g.type!==l.type?"scientific"===g.type?g:l:g.string.length!==l.string.length?g.string.length>l.string.length?g:l:g.string!==l.string?g.string<l.string?g:l:g.uid<l.uid?g:l:g}}m=[];for(h in e)m.push(e[h]);return m.sort(a.compare.names)}
var k=function(){function a(b,d,e,m,c,f,g){void 0===g&&(g=null);this.active=ko.observable(!1);this.nameA=ko.observable();this.nameB=ko.observable();this.sources=ko.observableArray();this.nameA(b);this.nameB(d);this.active(e);this.canFlip="function"===typeof g;this._flip=g;this._toggle=f;b=0;for(d=m.length;b<d;++b)this.sources.push(c[m[b]])}a.prototype.flip=function(){var a=this;this._flip(this.nameA().uid,this.nameB().uid,"html","type","string","citationStart").fail(function(a){return alert(a.message)}).done(function(d){a.nameA(d[0]);
a.nameB(d[1])})};a.prototype.toggle=function(){var a=this;this._toggle(this.nameA().uid,this.nameB().uid).fail(function(a){return alert(a.message)}).done(function(d){a.active(d)})};return a}();c.Relation=k;var n=function(){function c(b){this.citation=ko.observable("");this.progress=ko.observable(a.vm.async.EMPTY_PROMISE);this.string=ko.observable("");this.type=ko.observable("");this.name=b;this.citation(a.nomina.citation(b));this.string(a.nomina.uncite(b));this.type(b.type)}c.prototype.submit=function(){var b=
{},d=$.trim(this.string()),e=$.trim(this.citation()),m=this.type();if("scientific"===m)b.citationStart=0<e.length?d.length+1:0,b.string=0<e.length?d+" "+e:d;else if("vernacular"===m)b.citationStart=null,b.string=d;else return;b.type=m;this.progress(new a.vm.async.Promise(a.api.name.edit(this.name.uid,b).done(function(a){return location.href="/name/"+a.uid+"?"+String((new Date).getTime())}),!0,"Updating"))};return c}();c.EditName=n;var p=function(c){function b(d){c.call(this);this.contributionProgress=
ko.observable(a.vm.async.EMPTY_PROMISE);this.editName=ko.observable();this.hyponymies=ko.observableArray();this.imagesOther=ko.observableArray();this.imagesOtherProgress=ko.observable(a.vm.async.EMPTY_PROMISE);this.imagesSame=ko.observableArray();this.imagesSameProgress=ko.observable(a.vm.async.EMPTY_PROMISE);this.imagesSubtaxa=ko.observableArray();this.imagesSubtaxaProgress=ko.observable(a.vm.async.EMPTY_PROMISE);this.imagesSupertaxa=ko.observableArray();this.imagesSupertaxaProgress=ko.observable(a.vm.async.EMPTY_PROMISE);
this.name=ko.observable({uid:null});this.showChresonyms=ko.observable(!1);this.sourcesProgress=ko.observable(a.vm.async.EMPTY_PROMISE);this.subtaxa=ko.observableArray();this.supertaxa=ko.observableArray();this.synonymies=ko.observableArray();this.synonyms=ko.observableArray();this.taxonomyProgress=ko.observable(a.vm.async.EMPTY_PROMISE);var e=this;this.synonymsWithoutChresonyms=ko.computed(function(){return r(e.synonyms(),e.name())});this.hasChresonyms=ko.computed(function(){return e.synonymsWithoutChresonyms().length<
e.synonyms().length});this.synonymsSelected=ko.computed(function(){return e.showChresonyms()?e.synonyms():e.synonymsWithoutChresonyms()});this._loadName(d)}__extends(b,c);b.prototype.addConserved=function(){this._addRelation(!1,!1,a.nomina.uncite(this.name()))};b.prototype.addHyperonym=function(){this._addRelation(!0,!1,a.nomina.guessHyperonym(this.name()))};b.prototype.addHyponym=function(){this._addRelation(!0,!0,a.nomina.guessHyponym(this.name()))};b.prototype.addSuppressed=function(){this._addRelation(!1,
!0,a.nomina.uncite(this.name()))};b.prototype.cancelEdit=function(){this.editName(null)};b.prototype.deleteName=function(){confirm("Are you SURE you want to deactivate this name?")&&this.contributionProgress(new a.vm.async.Promise(a.api.name.deleteName(this.name().uid).done(function(a){return location.href="/"})))};b.prototype.edit=function(){this.editName(new n(this.name()))};b.prototype.loadOtherImages=function(){0===this.subtaxa().length&&0==this.supertaxa().length?this.imagesOtherProgress(new a.vm.async.Promise(a.api.defer().resolve(a.api.name.EMPTY_IMAGES_RESULT).promise())):
this._loadImages({other:!0},this.imagesOtherProgress,this.imagesOther,"other")};b.prototype.loadSameImages=function(a){function e(a){0===a.same.length&&b.loadSupertaxaImages()}void 0===a&&(a=!0);var b=this;this._sameImagesPromise=this._loadImages({},this.imagesSameProgress,this.imagesSame,"same");a&&this._sameImagesPromise.done(e)};b.prototype.loadSubtaxaImages=function(){0===this.subtaxa().length?this.imagesSubtaxaProgress(new a.vm.async.Promise(a.api.defer().resolve(a.api.name.EMPTY_IMAGES_RESULT).promise())):
this._loadImages({subtaxa:!0},this.imagesSubtaxaProgress,this.imagesSubtaxa,"subtaxa")};b.prototype.loadSupertaxaImages=function(){0===this.supertaxa().length?this.imagesSupertaxaProgress(new a.vm.async.Promise(a.api.defer().resolve(a.api.name.EMPTY_IMAGES_RESULT).promise())):this._loadImages({supertaxa:!0},this.imagesSupertaxaProgress,this.imagesSupertaxa,"supertaxa")};b.prototype.loadSources=function(){var d=this;this.sourcesProgress(new a.vm.async.Promise(a.api.name.taxonomySources(this.name().uid,
"html","string","canonicalName","type").done(function(e){d.hyponymies.removeAll();d.synonymies.removeAll();for(var b={},c={},f=0,g=e.names.length;f<g;++f){var h=e.names[f];b[h.uid]=h}f=0;for(g=e.sources.length;f<g;++f)h=e.sources[f],c[h.uri]=h;f=0;for(g=e.hyponymies.length;f<g;++f)h=e.hyponymies[f],d.hyponymies.push(new k(b[h[0]],b[h[1]],h[2],h[3],c,a.api.hyponymy.toggle));f=0;for(g=e.synonymies.length;f<g;++f)h=e.synonymies[f],d.synonymies.push(new k(b[h[0]],b[h[1]],h[2],h[3],c,a.api.synonymy.toggle,
a.api.synonymy.flip))})))};b.prototype.loadTaxonomy=function(){var d=this;this.subtaxa.removeAll();this.supertaxa.removeAll();this.synonyms.removeAll();this.hyponymies.removeAll();this.synonymies.removeAll();this.sourcesProgress(a.vm.async.EMPTY_PROMISE);this.taxonomyProgress(new a.vm.async.Promise(a.api.name.taxonomyUBio(this.name().uid,{subtaxa:"immediate",supertaxa:"immediate"},"canonicalName","citationStart","icon","html","names","root","string","type").done(function(e){var b=d.name().uid,c;a:{c=
e.taxa;for(var f=0,g=c.length;f<g;++f)for(var h=c[f],l=0,k=h.names.length;l<k;++l)if(h.names[l].uid===b){c=f;break a}c=-1}if(0<=c){h=e.taxa[c].names;f=0;for(g=h.length;f<g;++f)l=h[f],l.uid!==b&&d.synonyms.push(l);f=0;for(g=e.inclusions.length;f<g;++f)b=e.inclusions[f],b[0]===c?d.subtaxa.push(e.taxa[b[1]]):b[1]===c&&d.supertaxa.push(e.taxa[b[0]])}d.supertaxa.sort(a.compare.taxa);d.subtaxa.sort(a.compare.taxa);d.synonyms.sort(a.compare.names);d.loadSameImages(!0)})))};b.prototype.toggleChresonyms=function(){this.showChresonyms(!this.showChresonyms())};
b.prototype._addRelation=function(d,b,c){void 0===c&&(c="");var k=this,f=a.api.defer();this.cancelTaxonSearch();this.contributionProgress(new a.vm.async.Promise(f.promise(),!0,"Getting name"));c=new a.vm.name.Search(null,!0,c);this.taxonSearch(c);c.promise().progress(f.notify).fail(f.reject).done(function(c){function h(a){a?(f.resolve(null),k.loadTaxonomy()):f.reject({code:"invalid",message:d?"Could not include "+m.html+" in "+l.html+".":"Could not sink "+m.html+" into "+l.html+".",details:c})}if(c){f.notify(a.api.notifyMessage("Adding "+
(d?"hyponymy":"synonymy")));var l=b?k.name():c.canonicalName,m=b?c.canonicalName:k.name();(d?a.api.hyponymy.add:a.api.synonymy.add)(l.uid,m.uid).progress(f.notify).fail(f.reject).done(h)}else f.resolve(null)})};b.prototype._loadImages=function(d,b,c,k){d=a.api.name.images(this.name().uid,d,"credit","licenseURL","pngFiles","directNames","html").done(function(b){b=b[k];c.removeAll();for(var d=0,e=b.length;d<e;++d){var l=b[d];a:{for(var n=c(),p=0,q=n.length;p<q;++p)if(n[p].image.uid===l.uid){l=!0;break a}l=
!1}l||c.push(new a.vm.image.Image(b[d]))}});b(new a.vm.async.Promise(d));return d};b.prototype._loadName=function(b){var c=this;a.api.name.get(b,"citationStart","html","root","string","type");this.taxonomyProgress(new a.vm.async.Promise(a.api.name.get(b,"citationStart","html","root","string","type").done(function(a){c.name(a);c.loadTaxonomy();c.loadSameImages(!1)})))};return b}(q.Page);c.NamePage=p})(q.name||(q.name={}))})(a.page||(a.page={}))})(phylopic||(phylopic={}));ko.applyBindings(new phylopic.page.name.NamePage(NAME_UID));
